config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  devise_for :users

  # Nested resources for budgets and expenses
  resources :categories, only: [:new, :create]
  resources :budgets do
    resources :expenses, only: [:new, :create, :index]
  end

  # Expense-related routes
  resources :expenses, only: [:show, :destroy, :edit, :update]
  resources :goals, only: [:show, :index, :new, :create]
  # Custom routes
  get 'dashboard', to: 'pages#dashboard'
  get 'allexpenses', to: 'expenses#all_expenses'
  get 'categories/:category_id/expenses', to: 'expenses#category_expenses'
  get 'budgets/:id/track', to: 'budgets#track'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

    # Root route
    root to: "goals#index"

  # Actions route
  get "actions", to: "pages#actions", as: :actions
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if current_user %>
  <footer class="mobile-footer">
    <div class="footer-content">
      <%= link_to edit_user_registration_path(current_user.id) do %>
        <div class="footer-item">
          <i class="fas fa-user-circle"></i>
        </div>
      <% end %>
      <% if current_user.budgets.last.id.nil? %>
        <%= link_to budget_expenses_path(current_user.budgets.second_to_last.id) do %>
          <div class="footer-item">
            <i class="fas fa-chart-line"></i>
          </div>
        <% end %>
        <%= link_to new_budget_expense_path(current_user.budgets.second_to_last.id) do %>
          <div class="footer-item">
            <i class="fas fa-plus-circle"></i>
          </div>
        <% end %>
      <% else %>
        <%= link_to budget_expenses_path(current_user.budgets.last.id) do %>
          <div class="footer-item">
            <i class="fas fa-chart-line"></i>
          </div>
        <% end %>
        <%= link_to new_budget_expense_path(current_user.budgets.last.id) do %>
          <div class="footer-item">
            <i class="fas fa-plus-circle"></i>
          </div>
        <% end %>
      <% end %>

      <%= link_to budgets_path do %>
        <div class="footer-item">
          <i class="fas fa-wallet"></i>
        </div>
      <% end %>
      <%= link_to goals_path do %>
        <div class="footer-item">
          <i class="fas fa-bullseye"></i>
        </div>
      <% end %>
    </div>
  </footer>
<% end %>