config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  devise_for :users

  # Nested resources for budgets and expenses
  resources :categories, only: [:new, :create]
  resources :budgets do
    resources :expenses, only: [:new, :create, :index]
  end

  # Expense-related routes
  resources :expenses, only: [:show, :destroy, :edit, :update]
  resources :goals, only: [:show, :index, :new, :create]
  # Custom routes
  get 'dashboard', to: 'pages#dashboard'
  get 'allexpenses', to: 'expenses#all_expenses'
  get 'categories/:category_id/expenses', to: 'expenses#category_expenses'
  get 'budgets/:id/track', to: 'budgets#track'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

    # Root route
    root to: "goals#index"

  # Actions route
  get "actions", to: "pages#actions", as: :actions
end

app/views/pages/actions.html copy.erb
<div class="container">
  <div class="actions">
    <div class="btn">
      <%= link_to "ADD AN EXPENSE", new_budget_expense_path(current_user.budgets.last.id), class: "action-btn" %>
    </div>
    <div class="btn">
      <%= link_to "VIEW YOUR EXPENSES", budget_expenses_path(current_user.budgets.last.id), class: "action-btn" %>
    </div>
    <div class="btn">
      <%= link_to "BUDGET PLAN", budget_path(current_user.budgets.last.id), class: "action-btn" %>
    </div>
  </div>
</div>

app/views/pages/actions.html.erb
<div class="container">
  <div class="actions">
    
    <div class="btn">
      <%= link_to "ADD AN EXPENSE", new_budget_expense_path(current_user.budgets.last.id), class: "action-btn" %>
    </div>
    <div class="btn">
      <%= link_to "VIEW YOUR EXPENSES", budget_expenses_path(current_user.budgets.last.id), class: "action-btn" %>
    </div>
    <div class="btn">
      <%= link_to "BUDGET PLAN", budget_path(current_user.budgets.last.id), class: "action-btn" %>
    </div>
    <div class="btn">
      <%= link_to "NEW BUDGET", new_budget_path(current_user.budgets.last.id), class: "action-btn" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% if current_user.budgets.last.total_amount.zero? || current_user.budgets.last.total_amount.negative? %>
  <div class="broke">

    <p>CONGRATS HOMIE, you're broke</p>
  </div>
<% end %>
<div class="container">
<h1 class="text-center mt-3"><%= @current_budget.month %></h1>
  <div class="chart-container">

    <div class="chart">
      <% chart_labels = ["TOTAL EXPENSES", "REMAINING BUDGET"] %>
      <% chart_data = [@total_expenses, @remaining_budget] %>
      <div data-controller="chart" data-chart-labels-value="<%= chart_labels.to_json%>"
                               data-chart-data-value="<%= chart_data.to_json%>"
                              >
        <canvas data-chart-target="canvas" width="200" height="200">

        </div>
      </div>
      <% if @goal %>
        <div class="progress-container mt-5">
          <p class="progress-text">
            YOU HAVE MADE <%= @goal.target_progress.round(2) %>% PROGRESS TOWARDS YOUR <%= @goal.title.upcase %> TARGET
          </p>
          <div class="progress-bar-wrapper">
            <div class="progress-bar" style="width: <%= @goal.target_progress.round(2) %>%;"></div>
          </div>
        </div>

      <% end %>
    </div>

  </div>