config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  devise_for :users

  # Nested resources for budgets and expenses
  resources :categories, only: [:new, :create]
  resources :budgets do
    resources :expenses, only: [:new, :create, :index]
  end

  # Expense-related routes
  resources :expenses, only: [:show, :destroy, :edit, :update]
  resources :goals, only: [:show, :index, :new, :create]
  # Custom routes
  get 'dashboard', to: 'pages#dashboard'
  get 'allexpenses', to: 'expenses#all_expenses'
  get 'categories/:category_id/expenses', to: 'expenses#category_expenses'
  get 'budgets/:id/track', to: 'budgets#track'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

    # Root route
    root to: "goals#index"

  # Actions route
  get "actions", to: "pages#actions", as: :actions
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user

  def target_progress
    user.total_saved.fdiv(target_amount) * 100
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @goals = current_user.goals
  end

  def show
  end

  def new
    @goal = current_user.goals.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    if @goal.save!
      redirect_to goals_path, notice: ""
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:target_amount, :due_date, :title, :description)
  end
end

app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

app/views/goals/index.html.erb
  <div class="main-container h-100" >
    <div class="create-a-goal">
    <%= link_to "NEW GOAL", new_goal_path, class: "action-btn"%>
    </div>
      <% @goals.reverse.each do |goal| %>
    <div class="show">
    <div class="page-wrapper">
          <%# <p><%= current_user.total_saved %></p>
          <div class="goal-container">
            <p><%= goal.description %></p>
            <h2><%= goal.title.upcase %></h2>
            <%if goal.target_progress >= 100 %>
            <div class="glitch">
            <h4 class="electric-blue-flame">
            <br>
            <%= link_to "READY TO PURCHASE", new_budget_expense_path(current_user.budgets.last, goal_achieved: true, goal_id: goal.id), class: "electric-blue-flame" %>
            </h4>
            </div>
            <br>
            <p><i class="fa-solid fa-bullseye"></i>   <%= goal.target_amount %></p>
            <p><i class="fa-solid fa-calendar-days"></i>   <%= goal.due_date.strftime("%B %d, %Y") %></p>
          <% elsif goal.achieved %>
            <div class="glitch">
            <h4 class="electric-blue-flame">
            <br>
            SUCCESS
            </h4>

            </div>
          <% else %>
            <strong>
              <h1 class="target-progress"><%= goal.target_progress.round(0) %>%</h1>
            </strong>
            <br>
            <p><i class="fa-solid fa-bullseye"></i>   $<%= goal.target_amount %></p>
            <p><i class="fa-solid fa-calendar-days"></i>   <%= goal.due_date.strftime("%B %d, %Y") %></p>
          <% end %>
          </div>
      </div>
    </div>
      <% end %>
  </div>

app/views/goals/new.html.erb
<div class="pg-container">
  <div class="add-container">
    <div class="category">
    </div>
     <%= simple_form_for [@goal] do |f| %>
    <div class="price">
        <%= f.input :title %>
        <%= f.input :target_amount %>
        <%= f.input :description, label: "Motivation" %>
        <%= f.input :due_date %>

    </div>
    <div class="create-a-goal">
        <%= f.submit "SUBMIT", class: "action-btn" %>
    </div>
    <% end %>
  </div>
  <%# <%= link_to "BACK", root_path, class: "budget-btn" %>
</div>